### ISSUE TITLE
Register returns 500 error response

### ISSUE THREAD

**Issue by demattosanthony** [passwordless/passwordless-client-js#5]
After creating a token and passing it the Passwordless Client, a client does get registered but no authentication happens and a 500 error is returned. 

I know it is getting registered because when I try to register again with the same username an error is shown that a user already exists: 

See screenshots for details. 

<img width="1721" alt="Screen Shot 2022-08-04 at 11 05 46 AM" src="https://user-images.githubusercontent.com/70538060/182881495-50586fdd-740c-4f92-858b-23c007be07fa.png">

<img width="1698" alt="Screen Shot 2022-08-04 at 11 08 30 AM" src="https://user-images.githubusercontent.com/70538060/182882086-f90b0474-d5a8-4b01-bc4f-511fe7d56f73.png">

**Comment by abergs** [comment]
Hello @demattosanthony.
Thank you for reporting the error. 
Have you updated the API_KEY AND API_KEY_SECRET in the frontend and the backend nodejs application?

**Comment by beto-devnet** [comment]
Hello.

@demattosanthony did you find the solution for this?
I'm facing the same problem.

I generated the token properly, the Client object is configured well as in your screenshot and I'm getting the same error when endpoint  https://api.passwordless.dev/register/begin is called.

**Comment by abergs** [comment]
@beto-devnet I'm investigating your problem from our side.
Can you email me at anders@passwordless.dev and we can set up a quick video call or share some more screenshot details of your environment.

Would love to make this work for you!

**Comment by beto-devnet** [comment]
Update:

I was using an old version of the library, 0.1.0 instead of 0.2.0.

This happened when I installed the library using NPM
